on: push

jobs:
  checkout-files:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - run: npm -v
